### ISSUE TITLE
Active under development?

### ISSUE THREAD

**Issue by markrey** [srotya/tau#15]
hi @ambud ,

I was trying Hendrix and saw this project grew quite a lot.
Are you still actively developing it?

My own goal is to develop web app with simple rules engine on Kafka streaming.

Thanks,
Mark

**Comment by ambud** [comment]
The project is active, however I am working on other components in the eco system.

Both Nucleus (Rules Engine) and API (API Server) are dropwizard apps with REST APIs.

You can develop your own custom front-end to [Tau REST API Server](https://github.com/srotya/tau/tree/master/tau-api/src/main/java/com/srotya/tau/api).

Are referring to Kafka Streams?
If you are interested in writing your own engine from scratch, I would recommend reusing [Wraith](https://github.com/srotya/tau/tree/master/wraith-engine) which is what Tau is built on.

**Comment by markrey** [comment]
@ambud thanks for the quick response.
I am actually interested in couple of components together from Tau and can surely help you in developing the same.

My goal is to do below:
AMQP -> Kafka -> Customizable UI with rules engine ( like CEP ) -> 3rd party alerts.

I already developed AMQP to Kafka firehose.

I checked 
https://github.com/srotya/tau/tree/master/tau-ui

I can help improve that for sure.
I really liked the idea of native anomaly detection as well.

Great work!
just out of curiosity, is it part of Symantec product or your own private project?

**Comment by ambud** [comment]
Sounds good! I always welcome contributions! (Please open up pull requests)

Yes, both the UI implementations (Hendrix and Tau) were really not up to the mark, but I do recommend running the tau-ui (Polymer based) which will give you a rough idea about what the Rule Editor was suppose to look like (it can create and fetch rules from Tau API)

The [old UI](https://github.com/Symantec/hendrix/tree/current/hendrix-ui)'s (JSF based) also had a similar editor as well as a few graphs for flow rate, alert rate as well as live events and alerts.

**Backend:**
The backend (both API and Rule Engine) is fully functional the only restriction with Tau (not the case with Hendrix) is that it's currently not scale out, which is NOT a problem for most people unless you are really running heavy load. Tau-Nucleus can handle 44K EPS (events per second) on a Macbook Pro.

**Where to start:**
I highly recommend using the docker-compose template: https://github.com/srotya/tau/tree/master/install/configs/docker for Tau. This will fire up both API and Nucleus components along with mail server container. You should be able to pipe in events via the HTTP receiver.

**If you need Kafka integration, adding a Kafka consumer is really simple. I will try and add that hopefully this week.**

**Comment by ambud** [comment]
Also @markrey real-time anomaly detection is really difficult since anomaly / normal models can't be developed in real-time (specially at very high event volumes) due to memory and idempotency constraints.

I have a very high performance timeseries database to solve this problem. https://github.com/srotya/sidewinder 

Once models are developed in Sidewinder, you can apply them as rules in Tau.

**Comment by markrey** [comment]
Wow! I never actually checked sidewinder. That's really amazing. 
Any reason you are making it ground-up?

**Comment by ambud** [comment]
There isn't really anything out in open source that can meet real-world performance needs when it comes to metrics. InfluxDB can reach 200-300K on large servers before crashing.

More importantly when doing correlations like anomaly detection one needs really high throughput since most operations will be iterative and brute force, which drives the performance requirement.

Sidewinder is based on Facebook's Gorilla, a single server can handle millions of data points a second (read and write). It's purely in-memory, there's no disk based IO so performance is not a bottleneck.

The grafana plugin is extremely basic, needs a lot more features.

**Comment by markrey** [comment]
Just briefly went through the source. Quite neat! Lot more testing needed :) 
I have actually seen on Gorilla paper before but never got chance to look through practical implementation.

After going through couple of your repos, now i understand the ecosystem that you are trying to build! I have worked quite a lot on Storm, Squall, Streamsets and Nifi. 

Which type of library are you planning to use for correlations?

**Comment by markrey** [comment]
btw how do you load UI?

`polymer serve --open` after building doesn't work

**Comment by ambud** [comment]
Did you run ```bower install``` before running ```polymer serve --open```?

Additionally you will need the API server running to query rules (on localhost or some other address will need to edit the code)

**Comment by ambud** [comment]
Sidewinder core has good testing, haven't gotten a chance to fix testing for SQL (calcite) and binary protocols; those parts are still unfinished. 

Trying to get robust clustering working with Linea, Sidewinder will simply leverage Linea's clustering as will Tau (eventually)

**Comment by ambud** [comment]
Added instructions to run the docker-compose template:
https://github.com/srotya/tau/tree/master/install

Also, to run the UI: ```polymer serve -p 9998``` or any other port (8080 is taken by Nucleus)

**Comment by ambud** [comment]
@markrey were you able to try out the UI?

**Comment by markrey** [comment]
@ambud yepp I was able to try. Couple of bugs as API calls were failing.  
For example, when i try to create new Rule, it shows unknown error. 

I can document and create ticket if you like.

**Comment by ambud** [comment]
Please feel free to create a ticket. The bug should likely be in the UI, if you see it's in the API, please let me know.
